site_name: NetSentry Docs
site_url: https://mansoor00727.github.io/NetSentry-Network_Analyzer/
site_description: Documentation for Intelligent Network Traffic Analyzer
repo_url: https://github.com/mansoor00727/NetSentry-Network_Analyzer
repo_name: NetSentry-Network_Analyzer

theme:
  name: material
  palette: 
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.follow

nav:
  - Home: index.md
  - Project Handbook: handbook.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
